spring.profiles.active: development
---
spring:
  profiles: development
  data:
    mongodb:
      host: 192.168.1.55
      port: 27017
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.1.55:8181/uaa/user
    client:
      client-id: acme
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.55:8761/eureka/
---
server:
  port: 8883
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  enable-csrf: false
  ignored: /v1/orders/**
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.1.55}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8883
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/